# Generated by Django 5.1.3 on 2025-01-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='intrument_type',
        ),
        migrations.AddField(
            model_name='musician',
            name='instrument_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='directory.musician'),
        ),
    ]
